export const mandatoryTopicsLkMappingData = [
  [
    {
      name: "welcomePackage",
      description: "Welcome package",
      tools: "Office supplies, Access Card, Employee Guideline",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 2,
      link: "http://google.com",
    },
    {
      name: "locationTour",
      description: "Location tour",
      tools: "Presentation",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 2,
      link: "",
    },
    {
      name: "buddyIntroduction",
      description: "Buddy Introduction",
      tools: "Meeting",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 2,
      link: "",
    },
    {
      name: "companyPresentation",
      description: "IIS Romania presentation",
      tools: "Presentation",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 2,
      link: "",
    },
    {
      name: "orientationProgram",
      description: "New Hire Orientation Program",
      tools: "PPT",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 3,
      link: "",
    },
    {
      name: "discoverIpsos",
      description: "Discover Ipsos",
      tools: "ITC Platform",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "socialResponsibility",
      description: "Corporate Social Responsibility – Abridged version",
      tools: "ITC Platform",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "workplace behavior",
      description: "Appropriate workplace behavior",
      tools: "ITC Platform",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "greenBook",
      description: "Green Book Presentation",
      tools: "Ipsos Intranet",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "keyContacts",
      description: "Introduction key contacts",
      tools: "Meeting",
      group: 1,
      forManager: true,
      forSpecialist: true,
      timespanId: 4,
      responsibleId: 2,
      link: "",
    },
    {
      name: "specificProcedures",
      description:
        "Specific management procedures (RAF forms, Performance Appraisal Policy, " +
        "HC documentation, Budget documentation, Travel approvals, etc.)",
      tools: "Internal procedures, forms, documentation",
      group: 1,
      forManager: true,
      forSpecialist: false,
      timespanId: 4,
      responsibleId: 2,
      link: "",
    },
  ],
  [
    {
      name: "healthSafety",
      description: "Health and Safety at work",
      tools: "Intranet",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 1,
      link: "",
    },
    {
      name: "jobDescription",
      description: "Job description discussion",
      tools: "Job description form",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 1,
      responsibleId: 2,
      link: "",
    },
    {
      name: "presentProbationary",
      description: "Present the Probationary period goals plan",
      tools: "Probationary period form",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 4,
      responsibleId: 6,
      link: "",
    },
    {
      name: "qualitySecurity",
      description: "Quality and Info Security Essentials",
      tools: "E-learning / Email from Quality Team",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 4,
      responsibleId: 2,
      link: "",
    },
    {
      name: "securityAwareness",
      description: "Security Awareness 2017",
      tools: "ITC Platform",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "policiesProcedures",
      description: "Policies & Procedures - Book of Policies",
      tools: "Ipsos Intranet",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 7,
      responsibleId: 2,
      link: "",
    },
    {
      name: "gdpr",
      description: "General Data Protection Regulation (GDPR) / Data Privacy",
      tools: "Webinar",
      group: 2,
      forManager: true,
      forSpecialist: true,
      timespanId: 7,
      responsibleId: 7,
      link: "",
    },
  ],
  [
    {
      name: "mePlatform",
      description: "ME Platform",
      tools: "Intranet / ME Guideline",
      group: 3,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 5,
      link: "",
    },
    {
      name: "iTime",
      description: "iTime: Ipsos Time Tracking System",
      tools: "ITC Platform",
      group: 3,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 2,
      link: "",
    },
    {
      name: "iService",
      description: "iService",
      tools: "Intranet",
      group: 3,
      forManager: true,
      forSpecialist: true,
      timespanId: 4,
      responsibleId: 8,
      link: "",
    },
    {
      name: "iTalent",
      description: "iTalent",
      tools: "Presentation",
      group: 3,
      forManager: true,
      forSpecialist: true,
      timespanId: 6,
      responsibleId: 9,
      link: "",
    },
    {
      name: "itc",
      description: "Ipsos Training Center",
      tools: "ITC Platform",
      group: 3,
      forManager: true,
      forSpecialist: true,
      timespanId: 3,
      responsibleId: 3,
      link: "",
    },
  ],
  [
    {
      name: "communicationSkills",
      description: "Communication skills",
      tools: "ITC Platform",
      group: 4,
      forManager: false,
      forSpecialist: true,
      timespanId: 6,
      responsibleId: 2,
      link: "",
    },
    {
      name: "timeManagement",
      description: "Time Management",
      tools: "ITC Platform",
      group: 4,
      forManager: false,
      forSpecialist: true,
      timespanId: 6,
      responsibleId: 2,
      link: "",
    },
    {
      name: "clientInteractionModel",
      description: "Client interaction model overview ",
      tools: "ITC Platform",
      group: 4,
      forManager: false,
      forSpecialist: true,
      timespanId: 6,
      responsibleId: 2,
      link: "",
    },
    {
      name: "growLeaders",
      description: "GROW IIS Leaders",
      tools: "ITC Platform / In Class",
      group: 4,
      forManager: true,
      forSpecialist: false,
      timespanId: 8,
      responsibleId: 2,
      link: "",
    },
  ],
];
